const US_ZIP_PREFIXES: Record<string, { state: string; stateCode: string }> = {
  "005": { state: "New York", stateCode: "NY" },
  "006": { state: "Puerto Rico", stateCode: "PR" },
  "007": { state: "Puerto Rico", stateCode: "PR" },
  "008": { state: "Virgin Islands", stateCode: "VI" },
  "009": { state: "Puerto Rico", stateCode: "PR" },
  "010": { state: "Massachusetts", stateCode: "MA" },
  "011": { state: "Massachusetts", stateCode: "MA" },
  "012": { state: "Massachusetts", stateCode: "MA" },
  "013": { state: "Massachusetts", stateCode: "MA" },
  "014": { state: "Massachusetts", stateCode: "MA" },
  "015": { state: "Massachusetts", stateCode: "MA" },
  "016": { state: "Massachusetts", stateCode: "MA" },
  "017": { state: "Massachusetts", stateCode: "MA" },
  "018": { state: "Massachusetts", stateCode: "MA" },
  "019": { state: "Massachusetts", stateCode: "MA" },
  "020": { state: "Massachusetts", stateCode: "MA" },
  "021": { state: "Massachusetts", stateCode: "MA" },
  "022": { state: "Massachusetts", stateCode: "MA" },
  "023": { state: "Massachusetts", stateCode: "MA" },
  "024": { state: "Massachusetts", stateCode: "MA" },
  "025": { state: "Massachusetts", stateCode: "MA" },
  "026": { state: "Massachusetts", stateCode: "MA" },
  "027": { state: "Massachusetts", stateCode: "MA" },
  "028": { state: "Rhode Island", stateCode: "RI" },
  "029": { state: "Rhode Island", stateCode: "RI" },
  "030": { state: "New Hampshire", stateCode: "NH" },
  "031": { state: "New Hampshire", stateCode: "NH" },
  "032": { state: "New Hampshire", stateCode: "NH" },
  "033": { state: "New Hampshire", stateCode: "NH" },
  "034": { state: "New Hampshire", stateCode: "NH" },
  "035": { state: "Vermont", stateCode: "VT" },
  "036": { state: "Vermont", stateCode: "VT" },
  "037": { state: "Vermont", stateCode: "VT" },
  "038": { state: "Vermont", stateCode: "VT" },
  "039": { state: "Maine", stateCode: "ME" },
  "040": { state: "Maine", stateCode: "ME" },
  "041": { state: "Maine", stateCode: "ME" },
  "042": { state: "Maine", stateCode: "ME" },
  "043": { state: "Maine", stateCode: "ME" },
  "044": { state: "Maine", stateCode: "ME" },
  "045": { state: "Maine", stateCode: "ME" },
  "046": { state: "Maine", stateCode: "ME" },
  "047": { state: "Maine", stateCode: "ME" },
  "048": { state: "Maine", stateCode: "ME" },
  "049": { state: "Maine", stateCode: "ME" },
  "050": { state: "Vermont", stateCode: "VT" },
  "051": { state: "Vermont", stateCode: "VT" },
  "052": { state: "Vermont", stateCode: "VT" },
  "053": { state: "Vermont", stateCode: "VT" },
  "054": { state: "Vermont", stateCode: "VT" },
  "055": { state: "Massachusetts", stateCode: "MA" },
  "056": { state: "Vermont", stateCode: "VT" },
  "057": { state: "Vermont", stateCode: "VT" },
  "058": { state: "Vermont", stateCode: "VT" },
  "059": { state: "Vermont", stateCode: "VT" },
  "060": { state: "Connecticut", stateCode: "CT" },
  "061": { state: "Connecticut", stateCode: "CT" },
  "062": { state: "Connecticut", stateCode: "CT" },
  "063": { state: "Connecticut", stateCode: "CT" },
  "064": { state: "Connecticut", stateCode: "CT" },
  "065": { state: "Connecticut", stateCode: "CT" },
  "066": { state: "Connecticut", stateCode: "CT" },
  "067": { state: "Connecticut", stateCode: "CT" },
  "068": { state: "Connecticut", stateCode: "CT" },
  "069": { state: "Connecticut", stateCode: "CT" },
  "070": { state: "New Jersey", stateCode: "NJ" },
  "071": { state: "New Jersey", stateCode: "NJ" },
  "072": { state: "New Jersey", stateCode: "NJ" },
  "073": { state: "New Jersey", stateCode: "NJ" },
  "074": { state: "New Jersey", stateCode: "NJ" },
  "075": { state: "New Jersey", stateCode: "NJ" },
  "076": { state: "New Jersey", stateCode: "NJ" },
  "077": { state: "New Jersey", stateCode: "NJ" },
  "078": { state: "New Jersey", stateCode: "NJ" },
  "079": { state: "New Jersey", stateCode: "NJ" },
  "080": { state: "New Jersey", stateCode: "NJ" },
  "081": { state: "New Jersey", stateCode: "NJ" },
  "082": { state: "New Jersey", stateCode: "NJ" },
  "083": { state: "New Jersey", stateCode: "NJ" },
  "084": { state: "New Jersey", stateCode: "NJ" },
  "085": { state: "New Jersey", stateCode: "NJ" },
  "086": { state: "New Jersey", stateCode: "NJ" },
  "087": { state: "New Jersey", stateCode: "NJ" },
  "088": { state: "New Jersey", stateCode: "NJ" },
  "089": { state: "New Jersey", stateCode: "NJ" },
  "100": { state: "New York", stateCode: "NY" },
  "101": { state: "New York", stateCode: "NY" },
  "102": { state: "New York", stateCode: "NY" },
  "103": { state: "New York", stateCode: "NY" },
  "104": { state: "New York", stateCode: "NY" },
  "105": { state: "New York", stateCode: "NY" },
  "106": { state: "New York", stateCode: "NY" },
  "107": { state: "New York", stateCode: "NY" },
  "108": { state: "New York", stateCode: "NY" },
  "109": { state: "New York", stateCode: "NY" },
  "110": { state: "New York", stateCode: "NY" },
  "111": { state: "New York", stateCode: "NY" },
  "112": { state: "New York", stateCode: "NY" },
  "113": { state: "New York", stateCode: "NY" },
  "114": { state: "New York", stateCode: "NY" },
  "115": { state: "New York", stateCode: "NY" },
  "116": { state: "New York", stateCode: "NY" },
  "117": { state: "New York", stateCode: "NY" },
  "118": { state: "New York", stateCode: "NY" },
  "119": { state: "New York", stateCode: "NY" },
  "120": { state: "New York", stateCode: "NY" },
  "121": { state: "New York", stateCode: "NY" },
  "122": { state: "New York", stateCode: "NY" },
  "123": { state: "New York", stateCode: "NY" },
  "124": { state: "New York", stateCode: "NY" },
  "125": { state: "New York", stateCode: "NY" },
  "126": { state: "New York", stateCode: "NY" },
  "127": { state: "New York", stateCode: "NY" },
  "128": { state: "New York", stateCode: "NY" },
  "129": { state: "New York", stateCode: "NY" },
  "130": { state: "New York", stateCode: "NY" },
  "131": { state: "New York", stateCode: "NY" },
  "132": { state: "New York", stateCode: "NY" },
  "133": { state: "New York", stateCode: "NY" },
  "134": { state: "New York", stateCode: "NY" },
  "135": { state: "New York", stateCode: "NY" },
  "136": { state: "New York", stateCode: "NY" },
  "137": { state: "New York", stateCode: "NY" },
  "138": { state: "New York", stateCode: "NY" },
  "139": { state: "New York", stateCode: "NY" },
  "140": { state: "New York", stateCode: "NY" },
  "141": { state: "New York", stateCode: "NY" },
  "142": { state: "New York", stateCode: "NY" },
  "143": { state: "New York", stateCode: "NY" },
  "144": { state: "New York", stateCode: "NY" },
  "145": { state: "New York", stateCode: "NY" },
  "146": { state: "New York", stateCode: "NY" },
  "147": { state: "New York", stateCode: "NY" },
  "148": { state: "New York", stateCode: "NY" },
  "149": { state: "New York", stateCode: "NY" },
  "150": { state: "Pennsylvania", stateCode: "PA" },
  "151": { state: "Pennsylvania", stateCode: "PA" },
  "152": { state: "Pennsylvania", stateCode: "PA" },
  "153": { state: "Pennsylvania", stateCode: "PA" },
  "154": { state: "Pennsylvania", stateCode: "PA" },
  "155": { state: "Pennsylvania", stateCode: "PA" },
  "156": { state: "Pennsylvania", stateCode: "PA" },
  "157": { state: "Pennsylvania", stateCode: "PA" },
  "158": { state: "Pennsylvania", stateCode: "PA" },
  "159": { state: "Pennsylvania", stateCode: "PA" },
  "160": { state: "Pennsylvania", stateCode: "PA" },
  "161": { state: "Pennsylvania", stateCode: "PA" },
  "162": { state: "Pennsylvania", stateCode: "PA" },
  "163": { state: "Pennsylvania", stateCode: "PA" },
  "164": { state: "Pennsylvania", stateCode: "PA" },
  "165": { state: "Pennsylvania", stateCode: "PA" },
  "166": { state: "Pennsylvania", stateCode: "PA" },
  "167": { state: "Pennsylvania", stateCode: "PA" },
  "168": { state: "Pennsylvania", stateCode: "PA" },
  "169": { state: "Pennsylvania", stateCode: "PA" },
  "170": { state: "Pennsylvania", stateCode: "PA" },
  "171": { state: "Pennsylvania", stateCode: "PA" },
  "172": { state: "Pennsylvania", stateCode: "PA" },
  "173": { state: "Pennsylvania", stateCode: "PA" },
  "174": { state: "Pennsylvania", stateCode: "PA" },
  "175": { state: "Pennsylvania", stateCode: "PA" },
  "176": { state: "Pennsylvania", stateCode: "PA" },
  "177": { state: "Pennsylvania", stateCode: "PA" },
  "178": { state: "Pennsylvania", stateCode: "PA" },
  "179": { state: "Pennsylvania", stateCode: "PA" },
  "180": { state: "Pennsylvania", stateCode: "PA" },
  "181": { state: "Pennsylvania", stateCode: "PA" },
  "182": { state: "Pennsylvania", stateCode: "PA" },
  "183": { state: "Pennsylvania", stateCode: "PA" },
  "184": { state: "Pennsylvania", stateCode: "PA" },
  "185": { state: "Pennsylvania", stateCode: "PA" },
  "186": { state: "Pennsylvania", stateCode: "PA" },
  "187": { state: "Pennsylvania", stateCode: "PA" },
  "188": { state: "Pennsylvania", stateCode: "PA" },
  "189": { state: "Pennsylvania", stateCode: "PA" },
  "190": { state: "Pennsylvania", stateCode: "PA" },
  "191": { state: "Pennsylvania", stateCode: "PA" },
  "192": { state: "Pennsylvania", stateCode: "PA" },
  "193": { state: "Pennsylvania", stateCode: "PA" },
  "194": { state: "Pennsylvania", stateCode: "PA" },
  "195": { state: "Pennsylvania", stateCode: "PA" },
  "196": { state: "Pennsylvania", stateCode: "PA" },
  "197": { state: "Delaware", stateCode: "DE" },
  "198": { state: "Delaware", stateCode: "DE" },
  "199": { state: "Delaware", stateCode: "DE" },
  "200": { state: "District of Columbia", stateCode: "DC" },
  "201": { state: "Virginia", stateCode: "VA" },
  "202": { state: "District of Columbia", stateCode: "DC" },
  "203": { state: "District of Columbia", stateCode: "DC" },
  "204": { state: "District of Columbia", stateCode: "DC" },
  "205": { state: "District of Columbia", stateCode: "DC" },
  "206": { state: "Maryland", stateCode: "MD" },
  "207": { state: "Maryland", stateCode: "MD" },
  "208": { state: "Maryland", stateCode: "MD" },
  "209": { state: "Maryland", stateCode: "MD" },
  "210": { state: "Maryland", stateCode: "MD" },
  "211": { state: "Maryland", stateCode: "MD" },
  "212": { state: "Maryland", stateCode: "MD" },
  "213": { state: "Maryland", stateCode: "MD" },
  "214": { state: "Maryland", stateCode: "MD" },
  "215": { state: "Maryland", stateCode: "MD" },
  "216": { state: "Maryland", stateCode: "MD" },
  "217": { state: "West Virginia", stateCode: "WV" },
  "218": { state: "West Virginia", stateCode: "WV" },
  "219": { state: "West Virginia", stateCode: "WV" },
  "220": { state: "Virginia", stateCode: "VA" },
  "221": { state: "Virginia", stateCode: "VA" },
  "222": { state: "Virginia", stateCode: "VA" },
  "223": { state: "Virginia", stateCode: "VA" },
  "224": { state: "Virginia", stateCode: "VA" },
  "225": { state: "Virginia", stateCode: "VA" },
  "226": { state: "Virginia", stateCode: "VA" },
  "227": { state: "Virginia", stateCode: "VA" },
  "228": { state: "Virginia", stateCode: "VA" },
  "229": { state: "Virginia", stateCode: "VA" },
  "230": { state: "Virginia", stateCode: "VA" },
  "231": { state: "Virginia", stateCode: "VA" },
  "232": { state: "Virginia", stateCode: "VA" },
  "233": { state: "Virginia", stateCode: "VA" },
  "234": { state: "Virginia", stateCode: "VA" },
  "235": { state: "Virginia", stateCode: "VA" },
  "236": { state: "Virginia", stateCode: "VA" },
  "237": { state: "Virginia", stateCode: "VA" },
  "238": { state: "Virginia", stateCode: "VA" },
  "239": { state: "Virginia", stateCode: "VA" },
  "240": { state: "Virginia", stateCode: "VA" },
  "241": { state: "Virginia", stateCode: "VA" },
  "242": { state: "Virginia", stateCode: "VA" },
  "243": { state: "Virginia", stateCode: "VA" },
  "244": { state: "Virginia", stateCode: "VA" },
  "245": { state: "Virginia", stateCode: "VA" },
  "246": { state: "Virginia", stateCode: "VA" },
  "247": { state: "West Virginia", stateCode: "WV" },
  "248": { state: "West Virginia", stateCode: "WV" },
  "249": { state: "West Virginia", stateCode: "WV" },
  "250": { state: "West Virginia", stateCode: "WV" },
  "251": { state: "West Virginia", stateCode: "WV" },
  "252": { state: "West Virginia", stateCode: "WV" },
  "253": { state: "West Virginia", stateCode: "WV" },
  "254": { state: "West Virginia", stateCode: "WV" },
  "255": { state: "West Virginia", stateCode: "WV" },
  "256": { state: "West Virginia", stateCode: "WV" },
  "257": { state: "West Virginia", stateCode: "WV" },
  "258": { state: "West Virginia", stateCode: "WV" },
  "259": { state: "West Virginia", stateCode: "WV" },
  "260": { state: "West Virginia", stateCode: "WV" },
  "261": { state: "West Virginia", stateCode: "WV" },
  "262": { state: "West Virginia", stateCode: "WV" },
  "263": { state: "West Virginia", stateCode: "WV" },
  "264": { state: "West Virginia", stateCode: "WV" },
  "265": { state: "West Virginia", stateCode: "WV" },
  "266": { state: "West Virginia", stateCode: "WV" },
  "267": { state: "West Virginia", stateCode: "WV" },
  "268": { state: "West Virginia", stateCode: "WV" },
  "270": { state: "North Carolina", stateCode: "NC" },
  "271": { state: "North Carolina", stateCode: "NC" },
  "272": { state: "North Carolina", stateCode: "NC" },
  "273": { state: "North Carolina", stateCode: "NC" },
  "274": { state: "North Carolina", stateCode: "NC" },
  "275": { state: "North Carolina", stateCode: "NC" },
  "276": { state: "North Carolina", stateCode: "NC" },
  "277": { state: "North Carolina", stateCode: "NC" },
  "278": { state: "North Carolina", stateCode: "NC" },
  "279": { state: "North Carolina", stateCode: "NC" },
  "280": { state: "North Carolina", stateCode: "NC" },
  "281": { state: "North Carolina", stateCode: "NC" },
  "282": { state: "North Carolina", stateCode: "NC" },
  "283": { state: "North Carolina", stateCode: "NC" },
  "284": { state: "North Carolina", stateCode: "NC" },
  "285": { state: "North Carolina", stateCode: "NC" },
  "286": { state: "North Carolina", stateCode: "NC" },
  "287": { state: "North Carolina", stateCode: "NC" },
  "288": { state: "North Carolina", stateCode: "NC" },
  "289": { state: "North Carolina", stateCode: "NC" },
  "290": { state: "South Carolina", stateCode: "SC" },
  "291": { state: "South Carolina", stateCode: "SC" },
  "292": { state: "South Carolina", stateCode: "SC" },
  "293": { state: "South Carolina", stateCode: "SC" },
  "294": { state: "South Carolina", stateCode: "SC" },
  "295": { state: "South Carolina", stateCode: "SC" },
  "296": { state: "South Carolina", stateCode: "SC" },
  "297": { state: "South Carolina", stateCode: "SC" },
  "298": { state: "South Carolina", stateCode: "SC" },
  "299": { state: "South Carolina", stateCode: "SC" },
  "300": { state: "Georgia", stateCode: "GA" },
  "301": { state: "Georgia", stateCode: "GA" },
  "302": { state: "Georgia", stateCode: "GA" },
  "303": { state: "Georgia", stateCode: "GA" },
  "304": { state: "Georgia", stateCode: "GA" },
  "305": { state: "Georgia", stateCode: "GA" },
  "306": { state: "Georgia", stateCode: "GA" },
  "307": { state: "Georgia", stateCode: "GA" },
  "308": { state: "Georgia", stateCode: "GA" },
  "309": { state: "Georgia", stateCode: "GA" },
  "310": { state: "Georgia", stateCode: "GA" },
  "311": { state: "Georgia", stateCode: "GA" },
  "312": { state: "Georgia", stateCode: "GA" },
  "313": { state: "Georgia", stateCode: "GA" },
  "314": { state: "Georgia", stateCode: "GA" },
  "315": { state: "Georgia", stateCode: "GA" },
  "316": { state: "Georgia", stateCode: "GA" },
  "317": { state: "Georgia", stateCode: "GA" },
  "318": { state: "Georgia", stateCode: "GA" },
  "319": { state: "Georgia", stateCode: "GA" },
  "320": { state: "Florida", stateCode: "FL" },
  "321": { state: "Florida", stateCode: "FL" },
  "322": { state: "Florida", stateCode: "FL" },
  "323": { state: "Florida", stateCode: "FL" },
  "324": { state: "Florida", stateCode: "FL" },
  "325": { state: "Florida", stateCode: "FL" },
  "326": { state: "Florida", stateCode: "FL" },
  "327": { state: "Florida", stateCode: "FL" },
  "328": { state: "Florida", stateCode: "FL" },
  "329": { state: "Florida", stateCode: "FL" },
  "330": { state: "Florida", stateCode: "FL" },
  "331": { state: "Florida", stateCode: "FL" },
  "332": { state: "Florida", stateCode: "FL" },
  "333": { state: "Florida", stateCode: "FL" },
  "334": { state: "Florida", stateCode: "FL" },
  "335": { state: "Florida", stateCode: "FL" },
  "336": { state: "Florida", stateCode: "FL" },
  "337": { state: "Florida", stateCode: "FL" },
  "338": { state: "Florida", stateCode: "FL" },
  "339": { state: "Florida", stateCode: "FL" },
  "340": { state: "Virgin Islands", stateCode: "VI" },
  "341": { state: "Florida", stateCode: "FL" },
  "342": { state: "Florida", stateCode: "FL" },
  "344": { state: "Florida", stateCode: "FL" },
  "346": { state: "Florida", stateCode: "FL" },
  "347": { state: "Florida", stateCode: "FL" },
  "349": { state: "Florida", stateCode: "FL" },
  "350": { state: "Alabama", stateCode: "AL" },
  "351": { state: "Alabama", stateCode: "AL" },
  "352": { state: "Alabama", stateCode: "AL" },
  "354": { state: "Alabama", stateCode: "AL" },
  "355": { state: "Alabama", stateCode: "AL" },
  "356": { state: "Alabama", stateCode: "AL" },
  "357": { state: "Alabama", stateCode: "AL" },
  "358": { state: "Alabama", stateCode: "AL" },
  "359": { state: "Alabama", stateCode: "AL" },
  "360": { state: "Alabama", stateCode: "AL" },
  "361": { state: "Alabama", stateCode: "AL" },
  "362": { state: "Alabama", stateCode: "AL" },
  "363": { state: "Alabama", stateCode: "AL" },
  "364": { state: "Alabama", stateCode: "AL" },
  "365": { state: "Alabama", stateCode: "AL" },
  "366": { state: "Alabama", stateCode: "AL" },
  "367": { state: "Alabama", stateCode: "AL" },
  "368": { state: "Alabama", stateCode: "AL" },
  "369": { state: "Alabama", stateCode: "AL" },
  "370": { state: "Tennessee", stateCode: "TN" },
  "371": { state: "Tennessee", stateCode: "TN" },
  "372": { state: "Tennessee", stateCode: "TN" },
  "373": { state: "Tennessee", stateCode: "TN" },
  "374": { state: "Tennessee", stateCode: "TN" },
  "375": { state: "Tennessee", stateCode: "TN" },
  "376": { state: "Tennessee", stateCode: "TN" },
  "377": { state: "Tennessee", stateCode: "TN" },
  "378": { state: "Tennessee", stateCode: "TN" },
  "379": { state: "Tennessee", stateCode: "TN" },
  "380": { state: "Tennessee", stateCode: "TN" },
  "381": { state: "Tennessee", stateCode: "TN" },
  "382": { state: "Tennessee", stateCode: "TN" },
  "383": { state: "Tennessee", stateCode: "TN" },
  "384": { state: "Tennessee", stateCode: "TN" },
  "385": { state: "Tennessee", stateCode: "TN" },
  "386": { state: "Mississippi", stateCode: "MS" },
  "387": { state: "Mississippi", stateCode: "MS" },
  "388": { state: "Mississippi", stateCode: "MS" },
  "389": { state: "Mississippi", stateCode: "MS" },
  "390": { state: "Mississippi", stateCode: "MS" },
  "391": { state: "Mississippi", stateCode: "MS" },
  "392": { state: "Mississippi", stateCode: "MS" },
  "393": { state: "Mississippi", stateCode: "MS" },
  "394": { state: "Mississippi", stateCode: "MS" },
  "395": { state: "Mississippi", stateCode: "MS" },
  "396": { state: "Mississippi", stateCode: "MS" },
  "397": { state: "Mississippi", stateCode: "MS" },
  "400": { state: "Kentucky", stateCode: "KY" },
  "401": { state: "Kentucky", stateCode: "KY" },
  "402": { state: "Kentucky", stateCode: "KY" },
  "403": { state: "Kentucky", stateCode: "KY" },
  "404": { state: "Kentucky", stateCode: "KY" },
  "405": { state: "Kentucky", stateCode: "KY" },
  "406": { state: "Kentucky", stateCode: "KY" },
  "407": { state: "Kentucky", stateCode: "KY" },
  "408": { state: "Kentucky", stateCode: "KY" },
  "409": { state: "Kentucky", stateCode: "KY" },
  "410": { state: "Kentucky", stateCode: "KY" },
  "411": { state: "Kentucky", stateCode: "KY" },
  "412": { state: "Kentucky", stateCode: "KY" },
  "413": { state: "Kentucky", stateCode: "KY" },
  "414": { state: "Kentucky", stateCode: "KY" },
  "415": { state: "Kentucky", stateCode: "KY" },
  "416": { state: "Kentucky", stateCode: "KY" },
  "417": { state: "Kentucky", stateCode: "KY" },
  "418": { state: "Kentucky", stateCode: "KY" },
  "420": { state: "Kentucky", stateCode: "KY" },
  "421": { state: "Kentucky", stateCode: "KY" },
  "422": { state: "Kentucky", stateCode: "KY" },
  "423": { state: "Kentucky", stateCode: "KY" },
  "424": { state: "Kentucky", stateCode: "KY" },
  "425": { state: "Kentucky", stateCode: "KY" },
  "426": { state: "Kentucky", stateCode: "KY" },
  "427": { state: "Kentucky", stateCode: "KY" },
  "430": { state: "Ohio", stateCode: "OH" },
  "431": { state: "Ohio", stateCode: "OH" },
  "432": { state: "Ohio", stateCode: "OH" },
  "433": { state: "Ohio", stateCode: "OH" },
  "434": { state: "Ohio", stateCode: "OH" },
  "435": { state: "Ohio", stateCode: "OH" },
  "436": { state: "Ohio", stateCode: "OH" },
  "437": { state: "Ohio", stateCode: "OH" },
  "438": { state: "Ohio", stateCode: "OH" },
  "439": { state: "Ohio", stateCode: "OH" },
  "440": { state: "Ohio", stateCode: "OH" },
  "441": { state: "Ohio", stateCode: "OH" },
  "442": { state: "Ohio", stateCode: "OH" },
  "443": { state: "Ohio", stateCode: "OH" },
  "444": { state: "Ohio", stateCode: "OH" },
  "445": { state: "Ohio", stateCode: "OH" },
  "446": { state: "Ohio", stateCode: "OH" },
  "447": { state: "Ohio", stateCode: "OH" },
  "448": { state: "Ohio", stateCode: "OH" },
  "449": { state: "Ohio", stateCode: "OH" },
  "450": { state: "Ohio", stateCode: "OH" },
  "451": { state: "Ohio", stateCode: "OH" },
  "452": { state: "Ohio", stateCode: "OH" },
  "453": { state: "Ohio", stateCode: "OH" },
  "454": { state: "Ohio", stateCode: "OH" },
  "455": { state: "Ohio", stateCode: "OH" },
  "456": { state: "Ohio", stateCode: "OH" },
  "457": { state: "Ohio", stateCode: "OH" },
  "458": { state: "Ohio", stateCode: "OH" },
  "460": { state: "Indiana", stateCode: "IN" },
  "461": { state: "Indiana", stateCode: "IN" },
  "462": { state: "Indiana", stateCode: "IN" },
  "463": { state: "Indiana", stateCode: "IN" },
  "464": { state: "Indiana", stateCode: "IN" },
  "465": { state: "Indiana", stateCode: "IN" },
  "466": { state: "Indiana", stateCode: "IN" },
  "467": { state: "Indiana", stateCode: "IN" },
  "468": { state: "Indiana", stateCode: "IN" },
  "469": { state: "Indiana", stateCode: "IN" },
  "470": { state: "Indiana", stateCode: "IN" },
  "471": { state: "Indiana", stateCode: "IN" },
  "472": { state: "Indiana", stateCode: "IN" },
  "473": { state: "Indiana", stateCode: "IN" },
  "474": { state: "Indiana", stateCode: "IN" },
  "475": { state: "Indiana", stateCode: "IN" },
  "476": { state: "Indiana", stateCode: "IN" },
  "477": { state: "Indiana", stateCode: "IN" },
  "478": { state: "Indiana", stateCode: "IN" },
  "479": { state: "Indiana", stateCode: "IN" },
  "480": { state: "Michigan", stateCode: "MI" },
  "481": { state: "Michigan", stateCode: "MI" },
  "482": { state: "Michigan", stateCode: "MI" },
  "483": { state: "Michigan", stateCode: "MI" },
  "484": { state: "Michigan", stateCode: "MI" },
  "485": { state: "Michigan", stateCode: "MI" },
  "486": { state: "Michigan", stateCode: "MI" },
  "487": { state: "Michigan", stateCode: "MI" },
  "488": { state: "Michigan", stateCode: "MI" },
  "489": { state: "Michigan", stateCode: "MI" },
  "490": { state: "Michigan", stateCode: "MI" },
  "491": { state: "Michigan", stateCode: "MI" },
  "492": { state: "Michigan", stateCode: "MI" },
  "493": { state: "Michigan", stateCode: "MI" },
  "494": { state: "Michigan", stateCode: "MI" },
  "495": { state: "Michigan", stateCode: "MI" },
  "496": { state: "Michigan", stateCode: "MI" },
  "497": { state: "Michigan", stateCode: "MI" },
  "498": { state: "Michigan", stateCode: "MI" },
  "499": { state: "Michigan", stateCode: "MI" },
  "500": { state: "Iowa", stateCode: "IA" },
  "501": { state: "Iowa", stateCode: "IA" },
  "502": { state: "Iowa", stateCode: "IA" },
  "503": { state: "Iowa", stateCode: "IA" },
  "504": { state: "Iowa", stateCode: "IA" },
  "505": { state: "Iowa", stateCode: "IA" },
  "506": { state: "Iowa", stateCode: "IA" },
  "507": { state: "Iowa", stateCode: "IA" },
  "508": { state: "Iowa", stateCode: "IA" },
  "509": { state: "Iowa", stateCode: "IA" },
  "510": { state: "Iowa", stateCode: "IA" },
  "511": { state: "Iowa", stateCode: "IA" },
  "512": { state: "Iowa", stateCode: "IA" },
  "513": { state: "Iowa", stateCode: "IA" },
  "514": { state: "Iowa", stateCode: "IA" },
  "515": { state: "Iowa", stateCode: "IA" },
  "516": { state: "Iowa", stateCode: "IA" },
  "520": { state: "Iowa", stateCode: "IA" },
  "521": { state: "Iowa", stateCode: "IA" },
  "522": { state: "Iowa", stateCode: "IA" },
  "523": { state: "Iowa", stateCode: "IA" },
  "524": { state: "Iowa", stateCode: "IA" },
  "525": { state: "Iowa", stateCode: "IA" },
  "526": { state: "Iowa", stateCode: "IA" },
  "527": { state: "Iowa", stateCode: "IA" },
  "528": { state: "Iowa", stateCode: "IA" },
  "530": { state: "Wisconsin", stateCode: "WI" },
  "531": { state: "Wisconsin", stateCode: "WI" },
  "532": { state: "Wisconsin", stateCode: "WI" },
  "534": { state: "Wisconsin", stateCode: "WI" },
  "535": { state: "Wisconsin", stateCode: "WI" },
  "537": { state: "Wisconsin", stateCode: "WI" },
  "538": { state: "Wisconsin", stateCode: "WI" },
  "539": { state: "Wisconsin", stateCode: "WI" },
  "540": { state: "Wisconsin", stateCode: "WI" },
  "541": { state: "Wisconsin", stateCode: "WI" },
  "542": { state: "Wisconsin", stateCode: "WI" },
  "543": { state: "Wisconsin", stateCode: "WI" },
  "544": { state: "Wisconsin", stateCode: "WI" },
  "545": { state: "Wisconsin", stateCode: "WI" },
  "546": { state: "Wisconsin", stateCode: "WI" },
  "547": { state: "Wisconsin", stateCode: "WI" },
  "548": { state: "Wisconsin", stateCode: "WI" },
  "549": { state: "Wisconsin", stateCode: "WI" },
  "550": { state: "Minnesota", stateCode: "MN" },
  "551": { state: "Minnesota", stateCode: "MN" },
  "553": { state: "Minnesota", stateCode: "MN" },
  "554": { state: "Minnesota", stateCode: "MN" },
  "555": { state: "Minnesota", stateCode: "MN" },
  "556": { state: "Minnesota", stateCode: "MN" },
  "557": { state: "Minnesota", stateCode: "MN" },
  "558": { state: "Minnesota", stateCode: "MN" },
  "559": { state: "Minnesota", stateCode: "MN" },
  "560": { state: "Minnesota", stateCode: "MN" },
  "561": { state: "Minnesota", stateCode: "MN" },
  "562": { state: "Minnesota", stateCode: "MN" },
  "563": { state: "Minnesota", stateCode: "MN" },
  "564": { state: "Minnesota", stateCode: "MN" },
  "565": { state: "Minnesota", stateCode: "MN" },
  "566": { state: "Minnesota", stateCode: "MN" },
  "567": { state: "Minnesota", stateCode: "MN" },
  "569": { state: "District of Columbia", stateCode: "DC" },
  "570": { state: "South Dakota", stateCode: "SD" },
  "571": { state: "South Dakota", stateCode: "SD" },
  "572": { state: "South Dakota", stateCode: "SD" },
  "573": { state: "South Dakota", stateCode: "SD" },
  "574": { state: "South Dakota", stateCode: "SD" },
  "575": { state: "South Dakota", stateCode: "SD" },
  "576": { state: "South Dakota", stateCode: "SD" },
  "577": { state: "South Dakota", stateCode: "SD" },
  "580": { state: "North Dakota", stateCode: "ND" },
  "581": { state: "North Dakota", stateCode: "ND" },
  "582": { state: "North Dakota", stateCode: "ND" },
  "583": { state: "North Dakota", stateCode: "ND" },
  "584": { state: "North Dakota", stateCode: "ND" },
  "585": { state: "North Dakota", stateCode: "ND" },
  "586": { state: "North Dakota", stateCode: "ND" },
  "587": { state: "North Dakota", stateCode: "ND" },
  "588": { state: "North Dakota", stateCode: "ND" },
  "590": { state: "Montana", stateCode: "MT" },
  "591": { state: "Montana", stateCode: "MT" },
  "592": { state: "Montana", stateCode: "MT" },
  "593": { state: "Montana", stateCode: "MT" },
  "594": { state: "Montana", stateCode: "MT" },
  "595": { state: "Montana", stateCode: "MT" },
  "596": { state: "Montana", stateCode: "MT" },
  "597": { state: "Montana", stateCode: "MT" },
  "598": { state: "Montana", stateCode: "MT" },
  "599": { state: "Montana", stateCode: "MT" },
  "600": { state: "Illinois", stateCode: "IL" },
  "601": { state: "Illinois", stateCode: "IL" },
  "602": { state: "Illinois", stateCode: "IL" },
  "603": { state: "Illinois", stateCode: "IL" },
  "604": { state: "Illinois", stateCode: "IL" },
  "605": { state: "Illinois", stateCode: "IL" },
  "606": { state: "Illinois", stateCode: "IL" },
  "607": { state: "Illinois", stateCode: "IL" },
  "608": { state: "Illinois", stateCode: "IL" },
  "609": { state: "Illinois", stateCode: "IL" },
  "610": { state: "Illinois", stateCode: "IL" },
  "611": { state: "Illinois", stateCode: "IL" },
  "612": { state: "Illinois", stateCode: "IL" },
  "613": { state: "Illinois", stateCode: "IL" },
  "614": { state: "Illinois", stateCode: "IL" },
  "615": { state: "Illinois", stateCode: "IL" },
  "616": { state: "Illinois", stateCode: "IL" },
  "617": { state: "Illinois", stateCode: "IL" },
  "618": { state: "Illinois", stateCode: "IL" },
  "619": { state: "Illinois", stateCode: "IL" },
  "620": { state: "Kansas", stateCode: "KS" },
  "621": { state: "Kansas", stateCode: "KS" },
  "622": { state: "Kansas", stateCode: "KS" },
  "623": { state: "Kansas", stateCode: "KS" },
  "624": { state: "Kansas", stateCode: "KS" },
  "625": { state: "Kansas", stateCode: "KS" },
  "626": { state: "Kansas", stateCode: "KS" },
  "627": { state: "Kansas", stateCode: "KS" },
  "628": { state: "Kansas", stateCode: "KS" },
  "629": { state: "Kansas", stateCode: "KS" },
  "630": { state: "Missouri", stateCode: "MO" },
  "631": { state: "Missouri", stateCode: "MO" },
  "633": { state: "Missouri", stateCode: "MO" },
  "634": { state: "Missouri", stateCode: "MO" },
  "635": { state: "Missouri", stateCode: "MO" },
  "636": { state: "Missouri", stateCode: "MO" },
  "637": { state: "Missouri", stateCode: "MO" },
  "638": { state: "Missouri", stateCode: "MO" },
  "639": { state: "Missouri", stateCode: "MO" },
  "640": { state: "Missouri", stateCode: "MO" },
  "641": { state: "Missouri", stateCode: "MO" },
  "644": { state: "Missouri", stateCode: "MO" },
  "645": { state: "Missouri", stateCode: "MO" },
  "646": { state: "Missouri", stateCode: "MO" },
  "647": { state: "Missouri", stateCode: "MO" },
  "648": { state: "Missouri", stateCode: "MO" },
  "649": { state: "Missouri", stateCode: "MO" },
  "650": { state: "Missouri", stateCode: "MO" },
  "651": { state: "Missouri", stateCode: "MO" },
  "652": { state: "Missouri", stateCode: "MO" },
  "653": { state: "Missouri", stateCode: "MO" },
  "654": { state: "Missouri", stateCode: "MO" },
  "655": { state: "Missouri", stateCode: "MO" },
  "656": { state: "Missouri", stateCode: "MO" },
  "657": { state: "Missouri", stateCode: "MO" },
  "658": { state: "Missouri", stateCode: "MO" },
  "660": { state: "Kansas", stateCode: "KS" },
  "661": { state: "Kansas", stateCode: "KS" },
  "662": { state: "Kansas", stateCode: "KS" },
  "664": { state: "Kansas", stateCode: "KS" },
  "665": { state: "Kansas", stateCode: "KS" },
  "666": { state: "Kansas", stateCode: "KS" },
  "667": { state: "Kansas", stateCode: "KS" },
  "668": { state: "Kansas", stateCode: "KS" },
  "669": { state: "Kansas", stateCode: "KS" },
  "670": { state: "Kansas", stateCode: "KS" },
  "671": { state: "Kansas", stateCode: "KS" },
  "672": { state: "Kansas", stateCode: "KS" },
  "673": { state: "Kansas", stateCode: "KS" },
  "674": { state: "Kansas", stateCode: "KS" },
  "675": { state: "Kansas", stateCode: "KS" },
  "676": { state: "Kansas", stateCode: "KS" },
  "677": { state: "Kansas", stateCode: "KS" },
  "678": { state: "Kansas", stateCode: "KS" },
  "679": { state: "Kansas", stateCode: "KS" },
  "680": { state: "Nebraska", stateCode: "NE" },
  "681": { state: "Nebraska", stateCode: "NE" },
  "683": { state: "Nebraska", stateCode: "NE" },
  "684": { state: "Nebraska", stateCode: "NE" },
  "685": { state: "Nebraska", stateCode: "NE" },
  "686": { state: "Nebraska", stateCode: "NE" },
  "687": { state: "Nebraska", stateCode: "NE" },
  "688": { state: "Nebraska", stateCode: "NE" },
  "689": { state: "Nebraska", stateCode: "NE" },
  "690": { state: "Nebraska", stateCode: "NE" },
  "691": { state: "Nebraska", stateCode: "NE" },
  "692": { state: "Nebraska", stateCode: "NE" },
  "693": { state: "Nebraska", stateCode: "NE" },
  "700": { state: "Louisiana", stateCode: "LA" },
  "701": { state: "Louisiana", stateCode: "LA" },
  "703": { state: "Louisiana", stateCode: "LA" },
  "704": { state: "Louisiana", stateCode: "LA" },
  "705": { state: "Louisiana", stateCode: "LA" },
  "706": { state: "Louisiana", stateCode: "LA" },
  "707": { state: "Louisiana", stateCode: "LA" },
  "708": { state: "Louisiana", stateCode: "LA" },
  "710": { state: "Louisiana", stateCode: "LA" },
  "711": { state: "Louisiana", stateCode: "LA" },
  "712": { state: "Louisiana", stateCode: "LA" },
  "713": { state: "Louisiana", stateCode: "LA" },
  "714": { state: "Louisiana", stateCode: "LA" },
  "716": { state: "Arkansas", stateCode: "AR" },
  "717": { state: "Arkansas", stateCode: "AR" },
  "718": { state: "Arkansas", stateCode: "AR" },
  "719": { state: "Arkansas", stateCode: "AR" },
  "720": { state: "Arkansas", stateCode: "AR" },
  "721": { state: "Arkansas", stateCode: "AR" },
  "722": { state: "Arkansas", stateCode: "AR" },
  "723": { state: "Arkansas", stateCode: "AR" },
  "724": { state: "Arkansas", stateCode: "AR" },
  "725": { state: "Arkansas", stateCode: "AR" },
  "726": { state: "Arkansas", stateCode: "AR" },
  "727": { state: "Arkansas", stateCode: "AR" },
  "728": { state: "Arkansas", stateCode: "AR" },
  "729": { state: "Arkansas", stateCode: "AR" },
  "730": { state: "Oklahoma", stateCode: "OK" },
  "731": { state: "Oklahoma", stateCode: "OK" },
  "733": { state: "Texas", stateCode: "TX" },
  "734": { state: "Oklahoma", stateCode: "OK" },
  "735": { state: "Oklahoma", stateCode: "OK" },
  "736": { state: "Oklahoma", stateCode: "OK" },
  "737": { state: "Oklahoma", stateCode: "OK" },
  "738": { state: "Oklahoma", stateCode: "OK" },
  "739": { state: "Oklahoma", stateCode: "OK" },
  "740": { state: "Oklahoma", stateCode: "OK" },
  "741": { state: "Oklahoma", stateCode: "OK" },
  "743": { state: "Oklahoma", stateCode: "OK" },
  "744": { state: "Oklahoma", stateCode: "OK" },
  "745": { state: "Oklahoma", stateCode: "OK" },
  "746": { state: "Oklahoma", stateCode: "OK" },
  "747": { state: "Oklahoma", stateCode: "OK" },
  "748": { state: "Oklahoma", stateCode: "OK" },
  "749": { state: "Oklahoma", stateCode: "OK" },
  "750": { state: "Texas", stateCode: "TX" },
  "751": { state: "Texas", stateCode: "TX" },
  "752": { state: "Texas", stateCode: "TX" },
  "753": { state: "Texas", stateCode: "TX" },
  "754": { state: "Texas", stateCode: "TX" },
  "755": { state: "Texas", stateCode: "TX" },
  "756": { state: "Texas", stateCode: "TX" },
  "757": { state: "Texas", stateCode: "TX" },
  "758": { state: "Texas", stateCode: "TX" },
  "759": { state: "Texas", stateCode: "TX" },
  "760": { state: "Texas", stateCode: "TX" },
  "761": { state: "Texas", stateCode: "TX" },
  "762": { state: "Texas", stateCode: "TX" },
  "763": { state: "Texas", stateCode: "TX" },
  "764": { state: "Texas", stateCode: "TX" },
  "765": { state: "Texas", stateCode: "TX" },
  "766": { state: "Texas", stateCode: "TX" },
  "767": { state: "Texas", stateCode: "TX" },
  "768": { state: "Texas", stateCode: "TX" },
  "769": { state: "Texas", stateCode: "TX" },
  "770": { state: "Texas", stateCode: "TX" },
  "771": { state: "Texas", stateCode: "TX" },
  "772": { state: "Texas", stateCode: "TX" },
  "773": { state: "Texas", stateCode: "TX" },
  "774": { state: "Texas", stateCode: "TX" },
  "775": { state: "Texas", stateCode: "TX" },
  "776": { state: "Texas", stateCode: "TX" },
  "777": { state: "Texas", stateCode: "TX" },
  "778": { state: "Texas", stateCode: "TX" },
  "779": { state: "Texas", stateCode: "TX" },
  "780": { state: "Texas", stateCode: "TX" },
  "781": { state: "Texas", stateCode: "TX" },
  "782": { state: "Texas", stateCode: "TX" },
  "783": { state: "Texas", stateCode: "TX" },
  "784": { state: "Texas", stateCode: "TX" },
  "785": { state: "Texas", stateCode: "TX" },
  "786": { state: "Texas", stateCode: "TX" },
  "787": { state: "Texas", stateCode: "TX" },
  "788": { state: "Texas", stateCode: "TX" },
  "789": { state: "Texas", stateCode: "TX" },
  "790": { state: "Texas", stateCode: "TX" },
  "791": { state: "Texas", stateCode: "TX" },
  "792": { state: "Texas", stateCode: "TX" },
  "793": { state: "Texas", stateCode: "TX" },
  "794": { state: "Texas", stateCode: "TX" },
  "795": { state: "Texas", stateCode: "TX" },
  "796": { state: "Texas", stateCode: "TX" },
  "797": { state: "Texas", stateCode: "TX" },
  "798": { state: "Texas", stateCode: "TX" },
  "799": { state: "Texas", stateCode: "TX" },
  "800": { state: "Colorado", stateCode: "CO" },
  "801": { state: "Colorado", stateCode: "CO" },
  "802": { state: "Colorado", stateCode: "CO" },
  "803": { state: "Colorado", stateCode: "CO" },
  "804": { state: "Colorado", stateCode: "CO" },
  "805": { state: "Colorado", stateCode: "CO" },
  "806": { state: "Colorado", stateCode: "CO" },
  "807": { state: "Colorado", stateCode: "CO" },
  "808": { state: "Colorado", stateCode: "CO" },
  "809": { state: "Colorado", stateCode: "CO" },
  "810": { state: "Colorado", stateCode: "CO" },
  "811": { state: "Colorado", stateCode: "CO" },
  "812": { state: "Colorado", stateCode: "CO" },
  "813": { state: "Colorado", stateCode: "CO" },
  "814": { state: "Colorado", stateCode: "CO" },
  "815": { state: "Colorado", stateCode: "CO" },
  "816": { state: "Colorado", stateCode: "CO" },
  "820": { state: "Wyoming", stateCode: "WY" },
  "821": { state: "Wyoming", stateCode: "WY" },
  "822": { state: "Wyoming", stateCode: "WY" },
  "823": { state: "Wyoming", stateCode: "WY" },
  "824": { state: "Wyoming", stateCode: "WY" },
  "825": { state: "Wyoming", stateCode: "WY" },
  "826": { state: "Wyoming", stateCode: "WY" },
  "827": { state: "Wyoming", stateCode: "WY" },
  "828": { state: "Wyoming", stateCode: "WY" },
  "829": { state: "Wyoming", stateCode: "WY" },
  "830": { state: "Wyoming", stateCode: "WY" },
  "831": { state: "Wyoming", stateCode: "WY" },
  "832": { state: "Idaho", stateCode: "ID" },
  "833": { state: "Idaho", stateCode: "ID" },
  "834": { state: "Idaho", stateCode: "ID" },
  "835": { state: "Idaho", stateCode: "ID" },
  "836": { state: "Idaho", stateCode: "ID" },
  "837": { state: "Idaho", stateCode: "ID" },
  "838": { state: "Idaho", stateCode: "ID" },
  "840": { state: "Utah", stateCode: "UT" },
  "841": { state: "Utah", stateCode: "UT" },
  "842": { state: "Utah", stateCode: "UT" },
  "843": { state: "Utah", stateCode: "UT" },
  "844": { state: "Utah", stateCode: "UT" },
  "845": { state: "Utah", stateCode: "UT" },
  "846": { state: "Utah", stateCode: "UT" },
  "847": { state: "Utah", stateCode: "UT" },
  "850": { state: "Arizona", stateCode: "AZ" },
  "851": { state: "Arizona", stateCode: "AZ" },
  "852": { state: "Arizona", stateCode: "AZ" },
  "853": { state: "Arizona", stateCode: "AZ" },
  "855": { state: "Arizona", stateCode: "AZ" },
  "856": { state: "Arizona", stateCode: "AZ" },
  "857": { state: "Arizona", stateCode: "AZ" },
  "859": { state: "Arizona", stateCode: "AZ" },
  "860": { state: "Arizona", stateCode: "AZ" },
  "863": { state: "Arizona", stateCode: "AZ" },
  "864": { state: "Arizona", stateCode: "AZ" },
  "865": { state: "Arizona", stateCode: "AZ" },
  "870": { state: "New Mexico", stateCode: "NM" },
  "871": { state: "New Mexico", stateCode: "NM" },
  "872": { state: "New Mexico", stateCode: "NM" },
  "873": { state: "New Mexico", stateCode: "NM" },
  "874": { state: "New Mexico", stateCode: "NM" },
  "875": { state: "New Mexico", stateCode: "NM" },
  "877": { state: "New Mexico", stateCode: "NM" },
  "878": { state: "New Mexico", stateCode: "NM" },
  "879": { state: "New Mexico", stateCode: "NM" },
  "880": { state: "New Mexico", stateCode: "NM" },
  "881": { state: "New Mexico", stateCode: "NM" },
  "882": { state: "New Mexico", stateCode: "NM" },
  "883": { state: "New Mexico", stateCode: "NM" },
  "884": { state: "New Mexico", stateCode: "NM" },
  "885": { state: "Texas", stateCode: "TX" },
  "889": { state: "Nevada", stateCode: "NV" },
  "890": { state: "Nevada", stateCode: "NV" },
  "891": { state: "Nevada", stateCode: "NV" },
  "893": { state: "Nevada", stateCode: "NV" },
  "894": { state: "Nevada", stateCode: "NV" },
  "895": { state: "Nevada", stateCode: "NV" },
  "897": { state: "Nevada", stateCode: "NV" },
  "898": { state: "Nevada", stateCode: "NV" },
  "900": { state: "California", stateCode: "CA" },
  "901": { state: "California", stateCode: "CA" },
  "902": { state: "California", stateCode: "CA" },
  "903": { state: "California", stateCode: "CA" },
  "904": { state: "California", stateCode: "CA" },
  "905": { state: "California", stateCode: "CA" },
  "906": { state: "California", stateCode: "CA" },
  "907": { state: "California", stateCode: "CA" },
  "908": { state: "California", stateCode: "CA" },
  "910": { state: "California", stateCode: "CA" },
  "911": { state: "California", stateCode: "CA" },
  "912": { state: "California", stateCode: "CA" },
  "913": { state: "California", stateCode: "CA" },
  "914": { state: "California", stateCode: "CA" },
  "915": { state: "California", stateCode: "CA" },
  "916": { state: "California", stateCode: "CA" },
  "917": { state: "California", stateCode: "CA" },
  "918": { state: "California", stateCode: "CA" },
  "919": { state: "California", stateCode: "CA" },
  "920": { state: "California", stateCode: "CA" },
  "921": { state: "California", stateCode: "CA" },
  "922": { state: "California", stateCode: "CA" },
  "923": { state: "California", stateCode: "CA" },
  "924": { state: "California", stateCode: "CA" },
  "925": { state: "California", stateCode: "CA" },
  "926": { state: "California", stateCode: "CA" },
  "927": { state: "California", stateCode: "CA" },
  "928": { state: "California", stateCode: "CA" },
  "930": { state: "California", stateCode: "CA" },
  "931": { state: "California", stateCode: "CA" },
  "932": { state: "California", stateCode: "CA" },
  "933": { state: "California", stateCode: "CA" },
  "934": { state: "California", stateCode: "CA" },
  "935": { state: "California", stateCode: "CA" },
  "936": { state: "California", stateCode: "CA" },
  "937": { state: "California", stateCode: "CA" },
  "938": { state: "California", stateCode: "CA" },
  "939": { state: "California", stateCode: "CA" },
  "940": { state: "California", stateCode: "CA" },
  "941": { state: "California", stateCode: "CA" },
  "942": { state: "California", stateCode: "CA" },
  "943": { state: "California", stateCode: "CA" },
  "944": { state: "California", stateCode: "CA" },
  "945": { state: "California", stateCode: "CA" },
  "946": { state: "California", stateCode: "CA" },
  "947": { state: "California", stateCode: "CA" },
  "948": { state: "California", stateCode: "CA" },
  "949": { state: "California", stateCode: "CA" },
  "950": { state: "California", stateCode: "CA" },
  "951": { state: "California", stateCode: "CA" },
  "952": { state: "California", stateCode: "CA" },
  "953": { state: "California", stateCode: "CA" },
  "954": { state: "California", stateCode: "CA" },
  "955": { state: "California", stateCode: "CA" },
  "956": { state: "California", stateCode: "CA" },
  "957": { state: "California", stateCode: "CA" },
  "958": { state: "California", stateCode: "CA" },
  "959": { state: "California", stateCode: "CA" },
  "960": { state: "California", stateCode: "CA" },
  "961": { state: "California", stateCode: "CA" },
  "962": { state: "Armed Forces Pacific", stateCode: "AP" },
  "963": { state: "Armed Forces Pacific", stateCode: "AP" },
  "964": { state: "Armed Forces Pacific", stateCode: "AP" },
  "965": { state: "Armed Forces Pacific", stateCode: "AP" },
  "966": { state: "Armed Forces Pacific", stateCode: "AP" },
  "967": { state: "Hawaii", stateCode: "HI" },
  "968": { state: "Hawaii", stateCode: "HI" },
  "969": { state: "Guam", stateCode: "GU" },
  "970": { state: "Oregon", stateCode: "OR" },
  "971": { state: "Oregon", stateCode: "OR" },
  "972": { state: "Oregon", stateCode: "OR" },
  "973": { state: "Oregon", stateCode: "OR" },
  "974": { state: "Oregon", stateCode: "OR" },
  "975": { state: "Oregon", stateCode: "OR" },
  "976": { state: "Oregon", stateCode: "OR" },
  "977": { state: "Oregon", stateCode: "OR" },
  "978": { state: "Oregon", stateCode: "OR" },
  "979": { state: "Oregon", stateCode: "OR" },
  "980": { state: "Washington", stateCode: "WA" },
  "981": { state: "Washington", stateCode: "WA" },
  "982": { state: "Washington", stateCode: "WA" },
  "983": { state: "Washington", stateCode: "WA" },
  "984": { state: "Washington", stateCode: "WA" },
  "985": { state: "Washington", stateCode: "WA" },
  "986": { state: "Washington", stateCode: "WA" },
  "988": { state: "Washington", stateCode: "WA" },
  "989": { state: "Washington", stateCode: "WA" },
  "990": { state: "Washington", stateCode: "WA" },
  "991": { state: "Washington", stateCode: "WA" },
  "992": { state: "Washington", stateCode: "WA" },
  "993": { state: "Washington", stateCode: "WA" },
  "994": { state: "Washington", stateCode: "WA" },
  "995": { state: "Alaska", stateCode: "AK" },
  "996": { state: "Alaska", stateCode: "AK" },
  "997": { state: "Alaska", stateCode: "AK" },
  "998": { state: "Alaska", stateCode: "AK" },
  "999": { state: "Alaska", stateCode: "AK" },
};

export function lookupUSZip(zip: string): { state: string; stateCode: string } | null {
  const prefix = zip.substring(0, 3);
  return US_ZIP_PREFIXES[prefix] || null;
}

export function isUSZip(zip: string): boolean {
  return /^\d{5}(-\d{4})?$/.test(zip.trim());
}

export async function lookupPostalCode(postalCode: string, country?: string): Promise<{ city?: string; state?: string } | null> {
  try {
    const query = country
      ? `${postalCode}, ${country}`
      : postalCode;
    const res = await fetch(
      `https://nominatim.openstreetmap.org/search?postalcode=${encodeURIComponent(postalCode)}${country ? `&country=${encodeURIComponent(country)}` : ""}&format=json&limit=1&addressdetails=1`,
      { headers: { "User-Agent": "EliteLedgerCapital/1.0" } }
    );
    if (!res.ok) return null;
    const data = await res.json();
    if (!data || data.length === 0) return null;
    const addr = data[0]?.address;
    if (!addr) return null;
    return {
      city: addr.city || addr.town || addr.village || addr.municipality || addr.county,
      state: addr.state || addr.region || addr.province,
    };
  } catch {
    return null;
  }
}

export async function searchAddress(query: string): Promise<Array<{
  display: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
}>> {
  try {
    const res = await fetch(
      `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(query)}&format=json&limit=5&addressdetails=1`,
      { headers: { "User-Agent": "EliteLedgerCapital/1.0" } }
    );
    if (!res.ok) return [];
    const data = await res.json();
    return data
      .filter((item: any) => item.address)
      .map((item: any) => {
        const a = item.address;
        const road = [a.house_number, a.road].filter(Boolean).join(" ");
        return {
          display: item.display_name,
          address: road || item.display_name.split(",")[0],
          city: a.city || a.town || a.village || a.municipality || a.county || "",
          state: a.state || a.region || a.province || "",
          zipCode: a.postcode || "",
          country: a.country || "",
        };
      });
  } catch {
    return [];
  }
}
